FROM php:8.3-fpm

RUN apt-get update && \
    apt-get install -y git unzip libpq-dev libzip-dev && \
    pecl install redis && docker-php-ext-enable redis && \
    docker-php-ext-install pdo_pgsql zip sockets pcntl && \
    curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

WORKDIR /var/www/html
CMD ["php-fpm", "-F"]
