name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-interaction
        working-directory: ./src        # ← !!!

      - name: Show Laravel version
        run: php artisan --version
        working-directory: ./src        # ← !!!

      # при желании сразу добавьте автотесты
      # - name: Run PHPUnit tests
      #   run: php artisan test --parallel --env=testing
      #   working-directory: ./src

